# Generated by Django 5.2.8 on 2025-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('Budget', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=100)),
            ],
        ),
    ]
